export const wholeJobsArray = [
    '프론트엔드 개발자',
    '백엔드 개발자',
    '풀스택 개발자',
    '데브옵스 엔지니어',
    '데이터분석가',
    '클라우드 엔지니어',
    'IOS 앱 개발자',
    '안드로이드 앱 개발자',
    '데스크톱 개발자',
    '그래픽 개발자',
    '게임 개발자',
    '빅데이터 전문가',
    '데이터베이스 관리자',
    '정보보안 전문가',
    '소프트웨어 아키텍트(SA)',
    '웹 퍼블리셔(UI 개발자)',
    '임베디드 시스템 개발자',
    '데이터베이스 관리자',
    '자연어 처리 엔지니어',
    '컴퓨터 비전 엔지니어'
]

export const wholeStacksArray = [
    'react',
    'django',
    'javascript',
    'typescript',
    'python',
    'java',
    'spring',
    'aws',
    'git',
    'ios',
    'html',
    'css',
    'mysql',
    'sql',
    'linux',
    'android',
    'kotlin',
    'swift',
    'c/c++',
    'php',
    'docker',
    'github',
    'jpa',
    'typescript',
    'next.js',
    'node.js',
    'gcp',
    'django'
]